Repository rdkcentral/rdk-halif-test-power_manager, pull requests merged in 2024-11, with the labels that each got.

#29 gh #28 powerManager: L3 Test case Development
  src/test_l3_plat_power.c
Labels: L3 Work Element

#33 gh #32 Update UTCore version to 4.x
  build.sh
Labels: enhancement

#31 gh #30 Setting SetWakeupSrc to false causing issues
  src/test_l1_plat_power.c
  src/test_l2_plat_power.c
Labels: bug, L2 Work Element, L1 related issues
