Repository rdkcentral/rdk-halif-test-power_manager, pull requests merged in 2025-04, with the labels that each got.

#46 gh #42 update latest ut-raft, python raft and read me version
  README.md
  host/install.sh
Labels: enhancement

#45 gh #41 add launch json to run and debug L1 L2 automation cases in vs code
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/tasks.json
Labels: enhancement

#48 gh #47: suite navigator log module issue
  host/tests/L1_L2_TestCases/powermanager_L1_L2_testSetup.yml
  host/tests/L1_L2_TestCases/powermanager_L1_L2_tests.py
Labels: bug

#50 gh #49 binary copied to wrong directory
  host/tests/L1_L2_TestCases/powermanager_L1_L2_tests.py
Labels: bug, L2 Work Element, L1 related issues
